<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Viewing the people table</title>
</head>
<body>
    <style>
        body{
            font-family: Arial, Helvetica, sans-serif;
        }
    </style>
    <table>
        <tr>
            <th>ID</th>
            <th>Title</th>
            <th>Release Date</th>
            <th>Cast</th>
            <th>Director</th>
            <th>Total Gross</th>
        </tr>
    <?php
        
    include 'dbconnect.php';
	$search_term = '%'.$_POST['movie_title_search'].'%';
		
        //we start a try and catch block to attempt to connect to our database and run the query. If it fails, we see the error/exception generated by the catch
        try {
            $conn = new PDO("mysql:host=$servername;dbname=$database", $username, $password); //building a new PDO connection object
            
            $conn->setAttribute(PDO::ATTR_ERRMODE, PDO::ERRMODE_EXCEPTION); // set the PDO error mode to exception
            
            $sql = $conn->prepare("SELECT * FROM movies WHERE title LIKE :search ");
            $sql -> bindParam(':search', $search_term); //we bind this variable to the sql statement
            $sql -> execute(); //execute the statement
            //$sql->debugDumpParams();
            if($sql->rowCount()) { //check if we have results by counting rows
				 
			//For each result that we return, loop through the result and perform the echo statements.
            //Data will be formatted into a table
            //$row is an array with the fields for each record returned from the SELECT
                while ($row = $sql->fetch())//loop through the results to display them on screen
				{
                    echo '<tr>';
                    echo '<td>'. $row['id'] . '</td>';
                    echo '<td>'. $row['title'] . '</td>';
                    echo '<td>'. $row['release_date'] . '</td>';
                    echo '<td>'. $row['cast'] . '</td>';
                    echo '<td>'. $row['director'] . '</td>';
                    echo '<td>'. $row['total_gross'] . '</td>';
                    
                    echo '</tr>';
                }
            
            }
			else
			{
				echo "No rows returned";
			}
		}
        catch(PDOException $e)
            {
            echo "Error" . $e->getMessage(); //If we are not successful we will see an error
            }
        ?>

        </table>
</body>
</html>