<?php
session_start(); // important function to allow session variables  

if ($_SESSION['login'] != 1) {
    header("Location: login_form.html"); //send them to the form to login
}
?>

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Update person</title>
    
    <style>
    body{
        font-family:tahoma;
        background-color:#eee;

    }
    input[type=submit] {
        font-size:110%;
        background-color:green;
        color:white;
        border-radius: 4px;
    }
    select {
        width: 100%;
        padding: 16px 20px;
        border: none;
        border-radius: 4px;
        background-color: #fff;
        font-size:110%;
        margin:5px 0 5px 0;
        border:1px solid #333;
        }
</style>
</head>
<body>
    <?php
        
        //database connection variables for the database on your web server
        include 'dbconnect.php';

        //we start a try and catch block to attempt to connect to our database and run the query. If it fails, we see the error/exception generated by the catch
        
        try {
            if($_SERVER['REQUEST_METHOD'] == 'POST') //The update / submit button has been pressed
            {
                
                $conn = new PDO("mysql:host=$servername;dbname=$database", $username, $password); //building a new connection object
                // set the PDO error mode to exception
                $conn->setAttribute(PDO::ATTR_ERRMODE, PDO::ERRMODE_EXCEPTION);
                
                $id = $_SESSION['user_id'];
                
				$email = $_POST['email'];
                $password = $_POST['password'];

                $sql = $conn->prepare("UPDATE users SET email = :email, password = :password WHERE id = :id");
                $sql -> bindParam(':email', $email); 
				$sql -> bindParam(':password', $password);
                $sql -> bindParam(':id', $id);
                
                $sql -> execute(); //execute the statement
				//$sql->debugDumpParams();
				
                echo "Account updated";
            }
            else{
                $conn = new PDO("mysql:host=$servername;dbname=$database", $username, $password); //building a new connection object
                // set the PDO error mode to exception
                $conn->setAttribute(PDO::ATTR_ERRMODE, PDO::ERRMODE_EXCEPTION);

                $id = $_SESSION['user_id'];
                
                $sql = $conn->prepare("SELECT * FROM users WHERE id = ?");
                $sql -> bindValue(1, $id); //we bind this variable to the first ? in the sql statement

                $sql -> execute(); //execute the statement

                $row = $sql->fetch();
                
                //saving all of the data about the person so we can use them later to populate the form fields.              			
				$email = $row['email'];
                $password = $row['password'];
				
                //using an include to seperate the echo statement that handles the form
                //this allows us to seperate code so it is easier to manage
                include "update_account_form.php";

                echo '<hr><br>';
                
            }
        }
        catch(PDOException $e)
            {
            echo $e->getMessage(); //If we are not successful in connecting or running the query we will see an error
            }
        ?>


</body>
</html>