<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Update person</title>
    
    <style>
    body{
        font-family:tahoma;
        background-color:#eee;

    }
    input[type=submit] {
        font-size:110%;
        background-color:green;
        color:white;
        border-radius: 4px;
    }
    select {
        width: 100%;
        padding: 16px 20px;
        border: none;
        border-radius: 4px;
        background-color: #fff;
        font-size:110%;
        margin:5px 0 5px 0;
        border:1px solid #333;
        }
</style>
</head>
<body>
    <?php
        
        //database connection variables for the database on your web server
        include 'dbconnect.php';

        //we start a try and catch block to attempt to connect to our database and run the query. If it fails, we see the error/exception generated by the catch
        
        try {
            if($_SERVER['REQUEST_METHOD'] == 'POST') //The update / submit button has been pressed
            {
                
                $conn = new PDO("mysql:host=$servername;dbname=$database", $username, $password); //building a new connection object
                // set the PDO error mode to exception
                $conn->setAttribute(PDO::ATTR_ERRMODE, PDO::ERRMODE_EXCEPTION);
                
                $id = $_POST['id']; //the ID of the person we wanted to edit from the hidden form field
                
				$firstname = $_POST['first_name'];
				$lastname = $_POST['last_name'];
				$email = $_POST['email'];
				$gender = $_POST['gender'];
				$occupation = $_POST['occupation'];
				$skill = $_POST['skill'];
				$car = $_POST['car'];
				$education = $_POST['education'];
               

                $sql = $conn->prepare("UPDATE t_people SET first_name = :first_name, last_name = :last_name, email = :email, gender = :gender, occupation = :occupation, skill = :skill, car = :car, education = :education WHERE id = :id");
                $sql -> bindParam(':first_name', $firstname); 
				$sql -> bindParam(':last_name', $lastname);
				$sql -> bindParam(':email', $email); 
				$sql -> bindParam(':gender', $gender);
				$sql -> bindParam(':occupation', $occupation);
				$sql -> bindParam(':skill', $skill); 
				$sql -> bindParam(':car', $car); 
				$sql -> bindParam(':education', $education); 
				$sql -> bindParam(':id', $id); 
               
                
                $sql -> execute(); //execute the statement
				//$sql->debugDumpParams();
				
                echo "Person updated";
            }
            else{
                $conn = new PDO("mysql:host=$servername;dbname=$database", $username, $password); //building a new connection object
                // set the PDO error mode to exception
                $conn->setAttribute(PDO::ATTR_ERRMODE, PDO::ERRMODE_EXCEPTION);

                $id = $_GET['id']; //the ID of the person we want to edit from the URL
                
                $sql = $conn->prepare("SELECT * FROM t_people WHERE id = ?");
                $sql -> bindValue(1, $id); //we bind this variable to the first ? in the sql statement

                $sql -> execute(); //execute the statement

                $row = $sql->fetch();
                
                //saving all of the data about the person so we can use them later to populate the form fields.              			
				$firstname = $row['first_name'];
				$lastname = $row['last_name'];
				$email = $row['email'];
				$gender = $row['gender'];
				$occupation = $row['occupation'];
				$skill = $row['skill'];
				$car = $row['car'];
				$education = $row['education'];
				
				
                //using an include to seperate the echo statement that handles the form
                //this allows us to seperate code so it is easier to manage
                include "update_person_form.php";

                echo '<hr><br>';
                
            }
        }
        catch(PDOException $e)
            {
            echo $e->getMessage(); //If we are not successful in connecting or running the query we will see an error
            }
        ?>


</body>
</html>