<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Movies</title>
</head>
<body>
    <?php
        
        //database connection variables for the database on your web server
        include 'dbconnect.php';
        
        //saving all of the user's POST values from the the form submission to local variables
        $title = $_POST['title'];
        $release_date = $_POST['release_date'];
        $cast = $_POST['cast'];
        $director = $_POST['director'];
        $total_gross = $_POST['total_gross'];
       
        //we start a try and catch block to attempt to connect to our database and run the query. If it fails, we see the error/exception generated by the catch
        try {
            $conn = new PDO("mysql:host=$servername;dbname=$database", $username, $password); //building a new PDO connection object
           
            $conn->setAttribute(PDO::ATTR_ERRMODE, PDO::ERRMODE_EXCEPTION); // set the PDO error mode to exception

             // prepare sql and bind parameters
             //notice there is no need to include the ID field as it is autoincrement
            $stmt = $conn->prepare("INSERT INTO movies (title, release_date, cast, director, total_gross)
            VALUES (:title, :release_date, :cast, :director, :total_gross)");
            $stmt->bindParam(':title', $title);
            $stmt->bindParam(':release_date', $release_date);
            $stmt->bindParam(':cast', $cast);
            $stmt->bindParam(':director', $director);
            $stmt->bindParam(':total_gross', $total_gross);
            
            // use execute() to run the query
            $stmt->execute();
            
            echo "New table record created successfully"; 
            // If successful we will see this
            // you could then check PHPMyAdmin to see if the record was inserted
            }
        catch(PDOException $e)
            {
            echo "Error" . $e->getMessage(); //If we are not successful we will see an error
            }
        ?>


</body>
</html>